import type {
  AuditEvent,
  LedgerEntry,
  ProviderHealth,
  ProviderTransaction,
  VolumePoint,
} from "@/domain/types";

const ago = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const seedTransactions: ProviderTransaction[] = [
  {
    id: "txn_001",
    provider: "mobimoney",
    externalReference: "MM-240918-A81F",
    merchantReference: "ORD-10482",
    amountMinor: 82500,
    currency: "XAF",
    status: "successful",
    customerLabel: "Retail checkout",
    occurredAt: ago(18),
    settlementBatch: "CM-1809-AM",
  },
  {
    id: "txn_002",
    provider: "orange-pay",
    externalReference: "OP-240918-B92C",
    merchantReference: "ORD-10483",
    amountMinor: 145000,
    currency: "XAF",
    status: "successful",
    customerLabel: "Supplier invoice",
    occurredAt: ago(34),
    settlementBatch: "CM-1809-AM",
  },
  {
    id: "txn_003",
    provider: "pesa-link",
    externalReference: "PL-240918-C14D",
    merchantReference: "ORD-10484",
    amountMinor: 2265000,
    currency: "KES",
    status: "successful",
    customerLabel: "Marketplace payout",
    occurredAt: ago(49),
    settlementBatch: "KE-1809-01",
  },
  {
    id: "txn_004",
    provider: "mobimoney",
    externalReference: "MM-240918-D77E",
    merchantReference: "ORD-10485",
    amountMinor: 47500,
    currency: "XAF",
    status: "successful",
    customerLabel: "Service booking",
    occurredAt: ago(67),
    settlementBatch: "CM-1809-AM",
  },
  {
    id: "txn_005",
    provider: "orange-pay",
    externalReference: "OP-240918-E08A",
    merchantReference: "ORD-10486",
    amountMinor: 310000,
    currency: "XAF",
    status: "successful",
    customerLabel: "Wholesale order",
    occurredAt: ago(82),
    settlementBatch: "CM-1809-AM",
  },
  {
    id: "txn_006",
    provider: "mobimoney",
    externalReference: "MM-240918-F41B",
    merchantReference: "ORD-10487",
    amountMinor: 64000,
    currency: "XAF",
    status: "successful",
    customerLabel: "Subscription renewal",
    occurredAt: ago(105),
    settlementBatch: "CM-1809-AM",
  },
  {
    id: "txn_007",
    provider: "pesa-link",
    externalReference: "PL-240918-G16K",
    merchantReference: "ORD-10488",
    amountMinor: 985000,
    currency: "KES",
    status: "reversed",
    customerLabel: "Merchant reversal",
    occurredAt: ago(132),
    settlementBatch: "KE-1809-01",
  },
];

export const seedLedger: LedgerEntry[] = [
  {
    id: "led_001",
    externalReference: "MM-240918-A81F",
    merchantReference: "ORD-10482",
    amountMinor: 82500,
    currency: "XAF",
    status: "posted",
    account: "collections:cm:xaf",
    postedAt: ago(17),
  },
  {
    id: "led_002",
    externalReference: "OP-240918-B92C",
    merchantReference: "ORD-10483",
    amountMinor: 145000,
    currency: "XAF",
    status: "posted",
    account: "collections:cm:xaf",
    postedAt: ago(33),
  },
  {
    id: "led_003",
    externalReference: "PL-240918-C14D",
    merchantReference: "ORD-10484",
    amountMinor: 2265000,
    currency: "KES",
    status: "posted",
    account: "collections:ke:kes",
    postedAt: ago(47),
  },
  {
    id: "led_005",
    externalReference: "OP-240918-E08A",
    merchantReference: "ORD-10486",
    amountMinor: 300000,
    currency: "XAF",
    status: "posted",
    account: "collections:cm:xaf",
    postedAt: ago(80),
  },
  {
    id: "led_006",
    externalReference: "MM-240918-F41B",
    merchantReference: "ORD-10487",
    amountMinor: 64000,
    currency: "XAF",
    status: "pending",
    account: "collections:cm:xaf",
    postedAt: ago(103),
  },
  {
    id: "led_007",
    externalReference: "PL-240918-G16K",
    merchantReference: "ORD-10488",
    amountMinor: 985000,
    currency: "KES",
    status: "reversed",
    account: "collections:ke:kes",
    postedAt: ago(128),
  },
  {
    id: "led_orphan",
    externalReference: "INT-240918-ORPHAN",
    merchantReference: "ORD-10479",
    amountMinor: 29000,
    currency: "XAF",
    status: "posted",
    account: "collections:cm:xaf",
    postedAt: ago(156),
  },
];

export const providerHealth: ProviderHealth[] = [
  {
    provider: "mobimoney",
    displayName: "MobiMoney CM",
    successRate: 99.4,
    latencyMs: 284,
    webhookLagSeconds: 4,
    status: "healthy",
  },
  {
    provider: "orange-pay",
    displayName: "OrangePay Sandbox",
    successRate: 97.8,
    latencyMs: 621,
    webhookLagSeconds: 18,
    status: "degraded",
  },
  {
    provider: "pesa-link",
    displayName: "PesaLink Lab",
    successRate: 99.7,
    latencyMs: 198,
    webhookLagSeconds: 2,
    status: "healthy",
  },
];

export const seedVolume: VolumePoint[] = [
  { label: "00:00", matched: 55, exceptions: 4 },
  { label: "04:00", matched: 72, exceptions: 6 },
  { label: "08:00", matched: 128, exceptions: 9 },
  { label: "12:00", matched: 164, exceptions: 7 },
  { label: "16:00", matched: 143, exceptions: 5 },
  { label: "20:00", matched: 96, exceptions: 3 },
];

export const seedAudit: AuditEvent[] = [
  {
    id: "aud_001",
    action: "WEBHOOK_ACCEPTED",
    actor: "adapter:mobimoney",
    target: "MM-240918-A81F",
    detail: "Signature verified and event admitted to the processing queue.",
    timestamp: ago(18),
    outcome: "success",
  },
  {
    id: "aud_002",
    action: "IDEMPOTENCY_HIT",
    actor: "webhook-gateway",
    target: "evt_mm_91ca",
    detail: "Duplicate delivery blocked before the ledger write.",
    timestamp: ago(23),
    outcome: "warning",
  },
  {
    id: "aud_003",
    action: "RECONCILIATION_COMPLETED",
    actor: "scheduler:hourly",
    target: "run_20260918_0700",
    detail: "Provider exports compared with internal ledger entries.",
    timestamp: ago(51),
    outcome: "warning",
  },
];
